services:
  db:
    container_name: postgres-spring-boot
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: dineup
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    # Postgres uses port 5432 by default, if that is taken use 5332
    ports:
      - "5332:5432"
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d dineup"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  db: