### GET request to example server
GET http://localhost:8080/api/v1/

### Get request to menu items controller
GET http://localhost:8080/api/v1/menu-items

### Get request for menu item by id
GET http://localhost:8080/api/v1/menu-items/1

### Post request to menu items controller
POST http://localhost:8080/api/v1/menu-items
Content-Type: application/json

{
  "name": "Hambuger",
  "description": "Our seasoned beef patty placed in a pretzel bun. Served with lettuce, tomato, onion, pickles, and our housemade aioli",
  "price": 9.99,
  "imageUrl": "https://www.primaverakitchen.com/wp-content/uploads/2024/08/Hamburger-Recipe-7-500x500.jpg"
}
