@baseUrl = http://localhost:8080

### POST register account as CUSTOMER
POST {{baseUrl}}/api/v1/auth/register
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "User",
  "email": "testEmail@example.com",
  "password": "password123"
}

### POST authenticate customer account
POST {{baseUrl}}/api/v1/auth/authenticate
Content-Type: application/json

{
  "email": "testEmail@example.com",
  "password": "password123"
}

> {%
    if (response.status === 200 && response.body.token) {
        client.global.set("auth_token", response.body.token);
    } else {
        throw new Error("Authentication failed or token missing");
    }
%}

### POST register account as ADMIN
POST {{baseUrl}}/api/v1/auth/register
Content-Type: application/json

{
  "firstName": "Admin",
  "lastName": "User",
  "email": "admin@example.com",
  "password": "password1234",
  "role": "ADMIN"
}

### POST authenticate admin account
POST {{baseUrl}}/api/v1/auth/authenticate
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "password1234"
}

> {%
    if (response.status === 200 && response.body.token) {
        client.global.set("auth_token", response.body.token);
    } else {
        throw new Error("Authentication failed or token missing");
    }
%}

### GET request to Dine Up Application
GET {{baseUrl}}/api/v1/
Authorization: Bearer {{auth_token}}

### POST request for menu group
POST {{baseUrl}}/api/v1/menu-group
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Main Course"
}

### GET request for all menu groups
GET {{baseUrl}}/api/v1/menu-group
Authorization: Bearer {{auth_token}}

### GET request for all menu group by id
GET {{baseUrl}}/api/v1/menu-group/1
Authorization: Bearer {{auth_token}}

### PATCH request for menu group name
PATCH {{baseUrl}}/api/v1/menu-group/1
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Appetizers"
}

### DELETE menu group
DELETE {{baseUrl}}/api/v1/menu-group/1
Authorization: Bearer {{auth_token}}

### GET request for all menu items
GET {{baseUrl}}/api/v1/menu-items
Authorization: Bearer {{auth_token}}

### GET request for menu item by id
GET {{baseUrl}}/api/v1/menu-items/1
Authorization: Bearer {{auth_token}}

### POST request to add menu item
POST {{baseUrl}}/api/v1/menu-items
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "menuGroupId": 1,
  "name": "Hamburger",
  "description": "A beef patty placed inside a pretzel bun, served with lettuce, tomato, onion, pickles, and famous housemade aioli.",
  "price": 8.99
}

### PUT request to update menu item
PUT {{baseUrl}}/api/v1/menu-items/1
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Cheeseburger",
  "description": "A beef patty placed inside a pretzel bun, served with lettuce, tomato, onion, pickles, cheddar cheese, and famous housemade aioli.",
  "price": 9.99
}

### DELETE menu item
DELETE {{baseUrl}}/api/v1/menu-items/1
Authorization: Bearer {{auth_token}}

### POST to place order
POST {{baseUrl}}/api/v1/order
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "items": [
    {
      "menuItemId": 1,
      "quantity": 2
    },
    {
      "menuItemId": 2,
      "quantity": 1
    }
  ]
}

### GET all orders
GET {{baseUrl}}/api/v1/order
Authorization: Bearer {{auth_token}}

### GET customer fetches their order
GET {{baseUrl}}/api/v1/order/my-orders
Authorization: Bearer {{auth_token}}

### PATCH order status
PATCH {{baseUrl}}/api/v1/order
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "orderId": 1,
  "orderStatus": "COMPLETE"
}
